version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-demo-1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cuo5tr0pv58s"
s3_prefix = "sam-demo-1"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
