# YAML is a format just like JSON and XML, yet another markup language
# meta information
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
# contains metadata
Description: >
  sam-sqs-app

  Sample SAM Template for sam-sqs-app
  
# in globals we can define global variables, global settings which we want throughout our application
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

# here are the listed resources which are used for the application
Resources:
  # As of now only one resource is listed here which is a function
  HelloWorldFunction:
    # Type of that function is AWS Serverless function
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/ # Path of the lambda function
      Handler: app.lambdaHandler # the name of the file and the name of function written inside
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events: # It signifies for what all events this lambda would trigger, one API is listed here which is of get
        HelloWorld:
          Type: Api # the name of api is helloworld, type is API
          Properties:
            Path: /hello
            Method: get # It is a get call and the path is hello
  MySQSQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: samSqs.sqsLambdaHandler
      Runtime: nodejs16.x
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt MySqsQueue.Arn # MySQS has been registered here as a event
            BatchSize: 10
  MySqsQueue: # Whenever any message get pushed to this queue, the above lambda will be triggered.
    Type: AWS::SQS::Queue
# Output is for reference what will get printed on the console comes from here.
Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
